---
  - name: install packages
    yum:
      state: present
      name:
        - tcpdump
        - nano
        - iptables
        - iptables-services
    when: (ansible_hostname == "inetRouter")

  - name: enable iptables service
    service:
      name: iptables
      state: started 
      enabled: yes
    when: (ansible_hostname == "inetRouter")
  

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

  - name: deisable default route
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
    when: (ansible_hostname == "centralRouter")

  - name: add default gateway for centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.255.1
    when: (ansible_hostname == "centralRouter")
